"""Shared matplotlib style for thesis figures.

Centralises the figure appearance so every plot generated by
``scripts/make_figures.py`` shares the same palette, typography, and
grid conventions. Intentionally minimal — no seaborn, no custom
colour theory — so the style module itself is auditable.
"""

from __future__ import annotations

import matplotlib as mpl
import matplotlib.pyplot as plt

MODEL_ORDER: list[str] = ["LR", "MLP", "LSTM", "TFT"]

MODEL_COLOURS: dict[str, str] = {
    "LR":   "#555555",
    "MLP":  "#1f77b4",
    "LSTM": "#ff7f0e",
    "TFT":  "#2ca02c",
}

SPLIT_COLOURS: dict[str, str] = {
    "train": "#bdbdbd",
    "val":   "#7f7f7f",
    "test":  "#404040",
}


def apply_style() -> None:
    """Set matplotlib rcParams for all thesis figures."""
    mpl.rcParams.update({
        "figure.dpi": 150,
        "savefig.dpi": 300,
        "savefig.bbox": "tight",
        "font.family": "DejaVu Sans",
        "font.size": 10,
        "axes.titlesize": 10,
        "axes.labelsize": 9,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "legend.fontsize": 8,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.grid": True,
        "grid.linestyle": ":",
        "grid.linewidth": 0.5,
        "grid.alpha": 0.6,
        "lines.linewidth": 1.2,
        "text.usetex": False,
    })


def colour_for(model: str) -> str:
    return MODEL_COLOURS.get(model, "#000000")
